services:
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-network
    restart: always

  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword123
    networks:
      - app-network
    volumes:
      - mydata:/data/db
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mydata:
